metadata:
  engine: 4.0
  version: 1.2
  author: John Rowberry
  contact: johnrowberries@gmail.com
units:
  default_spread: 'cx'
  default_splay: 0
  default_width: 'cy'
  default_padding: 'cx'
  default_autobind: 10
  xspace: cx
  yspace: cy
  paddingy: yspace
  
points:
  zones:
    matrix:
      key:
        padding: default_padding
        spread: default_spread + 2
      anchor:
        shift: [100,-200]
        rotate: 0
      columns:
        pinky1:
          key.shift: [0,1]
          key.column_net: P2
        pink2:
          key.shift: [0,1]
          key.column_net: P3
        ring:
          key.splay: -3
          key.origin: [0,-30]
          key.shift: [0,1]
          key.column_net: P4
        middle:
          key.splay: -3
          key.origin: [0, -30]
          key.shift: [0, 1]
          key.column_net: P5
        pointer:
          key.splay: -3.5
          key.origin: [0, -20]
          key.shift: [0,1]
          key.column_net: P6
        pointer2:
          key.splay: 
          key.shift: [0,1]
          key.column_net: P7
      rows:
        bottom:
          row_net: P21
        middle:
          row_net: P20
        top:
          row_net: P19
        number:
          row_net: P18
    thumbfan:
      anchor:
        ref: matrix_pointer2_bottom
        shift: [0,-21]
      columns:
        near:
          key.splay: -15
          key.shift: [-1,0]
          key.column_net: P14
        home:
          key.shift: [0,0]
          key.column_net: P14
        far:
          key.shift: [1,0]
          key.column_net: P16
      rows:
        thumb:
          row_net: P20
    thumbfan2:
      anchor:
        ref: matrix_pointer2_bottom
        shift: [23,-8]
      columns:
        home2:
          key.splay: -15
          key.column_net: P14
        far2:
          key.shift: [1,0]
          key.column_net: P16
      rows:
        thumb2:
          row_net: P19
  rotate: 10
outlines:
  keyoutline:
  - what: rectangle
    where: true
    size: [xspace,yspace]
  faceplate_keys:
  - what: rectangle
    where: true
    size: [14,14]
  pcb_outline:
  - what: polygon
    operation: stack
    fillet: 5
    points:
    - ref: matrix_pinky1_top
      shift: [-15, 34]
    - ref: matrix_ring_top
      shift: [0,34]
    - ref: matrix_middle_top
      shift: [0, 34]
    - ref: matrix_pointer_top
      shift: [0,34]
    - ref: matrix_pointer2_top
      shift: [37, 35]
    - ref: matrix_pointer2_top
      shift: [37, -35]
    - ref: thumbfan_far_thumb
      shift: [14, 32]
    - ref: thumbfan_far_thumb
      shift: [14, -14]
    - ref: matrix_pointer_bottom
      shift: [1,-30]
    - ref: matrix_middle_bottom
      shift: [28, -15]
    - ref: matrix_middle_bottom
      shift: [0, -14]
    - ref: matrix_ring_bottom
      shift: [0, -14] 
    - ref: matrix_pinky1_bottom
      shift: [-15, -14]
  panel:
  - name: pcb_outline
  - operation: subtract
    name: keyoutline
  faceplate_panel:
  - name: pcb_outline
  - operation: subtract
    name: faceplate_keys

pcbs:
  boardPcb:
    outlines:
      main:
        outline: pcb_outline
    footprints:
      choc_hotswap:
        what: virginia2244/choc
        where: true
        params:
          traces: true
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: virginia2244/diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [9.5,-4]
          rotate: 90
      microcontroller:
        what: virginia2244/promicro
        params:
          reversable: true
          traces: true
        where:
          ref: matrix_pointer2_top
          shift: [23, 10]
      audio:
        what: trrs
        params:
          A: "GND"
          B: "P9"
          C: "P10"
          D: "VCC"
          reverse: true
        where:
          ref: matrix_pointer2_top
          shift: [31, -20]
          rotate: -90
      rgbB:
        what: epicpantalones/WS2812-2020
        params:
          din: "P8"
          vcc: "VCC"
          dout: "P15"
          gnd: "GND"
        where: true
        adjust:
          shift: [0, -4.7]

cases:
  faceplate:
  - what: outline
    name: faceplate_panel
    extrude: 1.5
